// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Textile_Invoice_App.Models;

#nullable disable

namespace Textile_Invoice_App.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328133615_AddLogoImageColumn")]
    partial class AddLogoImageColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Textile_Invoice_App.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccNm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillAdd1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillAdd2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillAdd3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillPincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrokerId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipAdd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransportId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId")
                        .HasName("PK__ACCOUNTS__05B22F604961FA81");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Textile_Invoice_App.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__APP_USER__F3BEEBFF9D9D931A");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Textile_Invoice_App.Models.CompanyProfile", b =>
                {
                    b.Property<int>("CompanyProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyProfileId"));

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gstin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("LogoImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Pan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyProfileId")
                        .HasName("PK__COMPANY___1522A7AFA8E44C72");

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("Textile_Invoice_App.Models.DesignMaster", b =>
                {
                    b.Property<int>("DesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignId"));

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DefaultRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DesignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HsnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignId")
                        .HasName("PK__DESIGN_M__C541F1369641403B");

                    b.ToTable("DesignMasters");
                });

            modelBuilder.Entity("Textile_Invoice_App.Models.InvoiceHeader", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int?>("BrokerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cgst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CgstPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ChallanDate")
                        .HasColumnType("date");

                    b.Property<string>("ChallanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Igst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IgstPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Roundup")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sgst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SgstPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransportId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId")
                        .HasName("PK__INVOICE___0CE91F0882C04866");

                    b.ToTable("InvoiceHeaders");
                });

            modelBuilder.Entity("Textile_Invoice_App.Models.InvoiceItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoChNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("DesignId")
                        .HasColumnType("int");

                    b.Property<string>("HsnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("PChNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pcs")
                        .HasColumnType("int");

                    b.Property<string>("Per")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId")
                        .HasName("PK__INVOICE___ADFD89A01201DE24");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("Textile_Invoice_App.Models.InvoiceNumberTracker", b =>
                {
                    b.Property<int>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentInvoiceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("CompanyProfileId")
                        .HasName("PK__INVOICE___1522A7AF3AA41D6A");

                    b.ToTable("InvoiceNumberTrackers");
                });

            modelBuilder.Entity("Textile_Invoice_App.Models.ServiceMaster", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int?>("CompanyProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId")
                        .HasName("PK__SERVICE___30358F5A6D97F45D");

                    b.ToTable("ServiceMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
